# This file was generated by GoReleaser. DO NOT EDIT.
cask "aurora" do
  name "aurora"
  desc "Aurora language CLI and LSP"
  homepage "https://github.com/guiferpa/aurora"
  version "0.1.8-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aurora"
  binary "aurorals"

  on_macos do
    on_intel do
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
      sha256 "842a3b40e5838cd75e1636d61488681c84440a1bcda4d2dec4b87469583a4f5c"
    end
    on_arm do
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
      sha256 "bc052f70e9dcc373fbff62b8c1595c77c0ae82f61f3f7535a0d41e5a6682e41f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_linux_amd64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
      sha256 "7bbf381548efe6d1f70c0eb1653a9d8e624650ce65f17eeba4daeb4be618cc75"
    end
    on_arm do
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_linux_arm64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
      sha256 "005550ec5fdfff069931964be50b42b551cf7139da5ed26bc365e21809d8433c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aurora", "#{staged_path}/aurorals"]
    end
  end

  # No zap stanza required
end
