# This file was generated by GoReleaser. DO NOT EDIT.
cask "aurora" do
  version "0.3.2-alpha"

  on_macos do
    on_intel do
      sha256 "033c2a7fd3925afc95b0b3ef3531fda883d30eea541d160cecb8d861edaaf187"
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
    end
    on_arm do
      sha256 "f8e6e41d5e0ca9b53cfb421aef9a9a9310718c26d0861147b5a8d95b09b94174"
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
    end
  end

  on_linux do
    on_intel do
      sha256 "617e0fe105cfca7ba0f0fb496a3791ed6b115f06aa33a9afd07a2d33fba53dfd"
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_linux_amd64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
    end
    on_arm do
      sha256 "9bf0d70a54c4e53d017b69ef1d29989a51288049edcb228e58b1003d6d929055"
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_linux_arm64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
    end
  end

  name "aurora"
  desc "Aurora language CLI and LSP"
  homepage "https://github.com/guiferpa/aurora"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aurora"
  binary "aurorals"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aurora", "#{staged_path}/aurorals"]
    end
  end

  # No zap stanza required

end
