# This file was generated by GoReleaser. DO NOT EDIT.
cask "aurora" do
  version "0.5.0-alpha"

  on_macos do
    on_intel do
      sha256 "97e21797028179f32f53d3f9b39d9872294449bffb7a71b30e74c4e406db0f55"
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
    end
    on_arm do
      sha256 "31ae9027335010e0b5e2e169c96ca8d4fd328a4b714a79a36033a2a15871fa71"
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
    end
  end

  on_linux do
    on_intel do
      sha256 "d28db333aad5cae3089c5dcb6b0e69a027d502bd0469244f7b12b15c83a97831"
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_linux_amd64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
    end
    on_arm do
      sha256 "13de6be95241770c59922b0bb22ecf6abbc3c804791d5cd5c4b1191ed7003930"
      url "https://github.com/guiferpa/aurora/releases/download/v#{version}/aurora_#{version}_linux_arm64.tar.gz",
        verified: "github.com/guiferpa/aurora/"
    end
  end

  name "aurora"
  desc "Aurora language CLI and LSP"
  homepage "https://github.com/guiferpa/aurora"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aurora"
  binary "aurorals"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aurora", "#{staged_path}/aurorals"]
    end
  end

  # No zap stanza required

end
